### ISSUE TITLE
Block scope / Single EXPR problem -- accessing included variable definitions

### ISSUE THREAD

**Issue by jcward** [jcward/haxe-includes#2]
Using the simple Include.file() mechanism (https://github.com/jcward/haxe-includes/blob/master/src/Include.hx#L17-L19) requires that only a single expression is parsed, which necessitaties surrounding multiple statements in an expression block: `{ }`

That, unfortunately, means the variables declared in the included code are not accessible outside the block. (Note that a [single line](https://github.com/jcward/haxe-includes/blob/master/includes/SingleStatement.hx#L2) of included code _is_ accessible and [doesn't suffer](https://github.com/jcward/haxe-includes/blob/master/src/Main.hx#L41-L45) from this problem.)

I have a couple ideas around this:

1) Perhaps it would be possible to [parse](https://github.com/jcward/haxe-includes/blob/master/src/Include.hx#L6-L10) the included code into individual statements (split on blocks and semi-colons), and call Context.parse() on each statement? But now I'm thinking that this won't work without being able to chain the scope somehow (otherwise, won't a variable declared in the first statement not be available in the second?)

2) Perhaps there is a way to access variables inside a block scope? e.g.

```
var expr = {
  var foo = "bar";
}
trace("Somehow I can access: "+foo);
```

**Comment by skial** [comment]
Hi @jcward, I've just got around to looking at this repo.

My first thought when I came across this issue was you might want to try adding the `@:mergeBlock` metadata before returning a block expression, so it _should_ exist within the same scope the method was called.

**Comment by jcward** [comment]
@skial fantastic, Brendon! I didn't know about `@:mergeBlock` which is exactly why I posed the repo / questions. Thanks!
